#!/bin/bash
# Back the photo library up to S3-compatible object storage, encrypted, then
# apply the retention policy.
#
#   ./scripts/backup.sh
#
# Run by immich-backup.timer. Safe to run by hand and safe to interrupt -
# restic writes its index as it goes, so an interrupted run is picked up by the
# next one rather than starting over. The first run uploads the whole library
# and can take days; see RESTIC_UPLOAD_LIMIT_KIB in .env.bash.
set -euo pipefail

source "$(dirname "$0")/restic-env.sh"
_restic_load_env
require_mount

########################################
# Is the database dump fresh?
########################################
# The photos are only half of a restorable Immich. The other half - albums,
# people, faces, metadata, shared links - is in Postgres, and is captured by
# Immich's own nightly dump into UPLOAD_LOCATION/backups rather than by copying
# the Postgres data directory, which would not restore.
#
# Checked BEFORE the snapshot but reported AFTER it: a stale dump is no reason
# to skip backing up the photos, and it is every reason to raise an alert.
dump_problem=""
max_age_h="${IMMICH_DB_DUMP_MAX_AGE_HOURS:-26}"
if [[ "${max_age_h}" != "0" ]]; then
  newest="$(find "${UPLOAD_LOCATION}/backups" -maxdepth 1 -type f \
              -name 'immich-db-backup-*.sql.gz' -printf '%T@ %p\n' 2>/dev/null \
            | sort -rn | head -1 || true)"
  if [[ -z "${newest}" ]]; then
    dump_problem="No database dump in ${UPLOAD_LOCATION}/backups.
Enable it under Administration -> Settings -> Backup Settings. Without it this
backup holds photos and nothing else: no albums, no people, no metadata."
  else
    dump_ts="${newest%% *}"; dump_ts="${dump_ts%.*}"
    dump_file="${newest#* }"
    dump_age_h=$(( ( $(date +%s) - dump_ts ) / 3600 ))
    echo "Newest database dump: $(basename "${dump_file}") (${dump_age_h}h old)"
    if (( dump_age_h > max_age_h )); then
      dump_problem="Newest database dump is ${dump_age_h}h old (limit ${max_age_h}h):
  ${dump_file}
Immich's dump job has stopped running. The snapshot above is good apart
from the database, which is ${dump_age_h}h behind the photos."
    fi
  fi
fi

ensure_repo

########################################
# Snapshot
########################################
declare -a exclude_args
restic_exclude_args exclude_args
read -ra scan_flags <<< "${RESTIC_SCAN_FLAGS:---ignore-inode}"

limit_args=()
if [[ "${RESTIC_UPLOAD_LIMIT_KIB:-0}" != "0" ]]; then
  limit_args=( --limit-upload "${RESTIC_UPLOAD_LIMIT_KIB}" )
fi

echo
echo "Backing up ${UPLOAD_LOCATION}"
echo "  library/        originals (storage template on)"
echo "  upload/         originals (storage template off) and uploads in flight"
echo "  profile/        profile images"
echo "  backups/        Immich's database dumps"
excluded_names=()
for a in "${exclude_args[@]}"; do
  [[ "$a" == "--exclude" ]] || excluded_names+=( "$(basename "$a")/" )
done
if ((${#excluded_names[@]})); then
  echo "  excluded:       ${excluded_names[*]} (regenerated by Immich)"
fi
echo

# The version tag records which Immich wrote the snapshot. A dump can only be
# loaded by the release that produced it, so a restore needs to know.
restic_run backup \
  "${UPLOAD_LOCATION}" \
  --tag immich \
  --tag "immich-${IMMICH_VERSION}" \
  "${exclude_args[@]}" \
  "${scan_flags[@]}" \
  "${limit_args[@]}" \
  --verbose

########################################
# Retention
########################################
echo
echo "Applying retention policy..."
# --prune actually reclaims space; without it forget only drops the snapshot
# references and the data stays.
restic_run forget \
  --tag immich \
  --keep-daily   "${RESTIC_KEEP_DAILY:-7}" \
  --keep-weekly  "${RESTIC_KEEP_WEEKLY:-5}" \
  --keep-monthly "${RESTIC_KEEP_MONTHLY:-12}" \
  --keep-yearly  "${RESTIC_KEEP_YEARLY:-75}" \
  --prune

echo
echo "Structural check..."
# Metadata only - fast, runs every time. The expensive check that re-reads
# actual data is scripts/check-backup.sh, on its own weekly timer.
restic_run check

echo
restic_run snapshots --tag immich --latest 3

if [[ -n "${dump_problem}" ]]; then
  echo
  echo "############################################################" >&2
  echo "# DATABASE DUMP PROBLEM                                    #" >&2
  echo "############################################################" >&2
  echo "${dump_problem}" >&2
  exit 1
fi

echo "Backup complete."
